name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Get dependencies
        run: go mod tidy
      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "以下のファイルがgofmtされていません:"
            gofmt -s -l .
            exit 1
          fi
      - name: Run vet
        run: go vet ./...
      - name: Run tests
        run: go test -v ./...
      - name: Test build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o /tmp/kizuna_bot-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o /tmp/kizuna_bot-windows-amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o /tmp/kizuna_bot-darwin-amd64 .
          echo "全プラットフォームでのビルドが成功しました"
